
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int REL_OP = 16;
  public static final int STRING_TEXT = 26;
  public static final int INCREMENT = 5;
  public static final int CONST = 2;
  public static final int SLASH = 37;
  public static final int COMMENT = 14;
  public static final int CASE = 39;
  public static final int SMALLER = 33;
  public static final int GREATER = 34;
  public static final int OR_OPR = 43;
  public static final int CLOSE_SQUARE = 23;
  public static final int FOR = 41;
  public static final int MINUS = 6;
  public static final int TYPE = 31;
  public static final int OPEN_PARAN = 20;
  public static final int ASTRISK = 10;
  public static final int COMMA = 30;
  public static final int LESS_EQUAL = 36;
  public static final int OPEN_SQUARE = 22;
  public static final int OPEN_CURLY = 27;
  public static final int PLUS = 4;
  public static final int IF = 8;
  public static final int DOT = 29;
  public static final int AND_OP = 15;
  public static final int EOF = 0;
  public static final int RETURN = 17;
  public static final int EQUAL = 3;
  public static final int GREATER_EQUAL = 24;
  public static final int error = 1;
  public static final int PERCENT = 13;
  public static final int SEMI_COLON = 19;
  public static final int SWITCH = 38;
  public static final int CLOSE_PARAN = 21;
  public static final int IMPORT = 45;
  public static final int COLON = 18;
  public static final int CLOSE_CURLY = 28;
  public static final int ELSE = 12;
  public static final int FUNC = 9;
  public static final int PACKAGE = 44;
  public static final int DEFAULT = 40;
  public static final int SINGLE_OR = 25;
  public static final int STRUCT = 42;
  public static final int INT_LIT = 32;
  public static final int VAR = 7;
  public static final int COLON_EQUAL = 11;
  public static final int EQUAL_EQUAL = 35;
  public static final int IDENTIFIER = 46;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONST",
  "EQUAL",
  "PLUS",
  "INCREMENT",
  "MINUS",
  "VAR",
  "IF",
  "FUNC",
  "ASTRISK",
  "COLON_EQUAL",
  "ELSE",
  "PERCENT",
  "COMMENT",
  "AND_OP",
  "REL_OP",
  "RETURN",
  "COLON",
  "SEMI_COLON",
  "OPEN_PARAN",
  "CLOSE_PARAN",
  "OPEN_SQUARE",
  "CLOSE_SQUARE",
  "GREATER_EQUAL",
  "SINGLE_OR",
  "STRING_TEXT",
  "OPEN_CURLY",
  "CLOSE_CURLY",
  "DOT",
  "COMMA",
  "TYPE",
  "INT_LIT",
  "SMALLER",
  "GREATER",
  "EQUAL_EQUAL",
  "LESS_EQUAL",
  "SLASH",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "FOR",
  "STRUCT",
  "OR_OPR",
  "PACKAGE",
  "IMPORT",
  "IDENTIFIER"
  };
}

